# fly.toml app configuration file generated for bgg-sorter on 2025-10-12T03:43:34-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bgg-sorter'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile'

[deploy]
  release_command = './bin/bgg_sorter eval Core.Release.migrate()'

[env]
  ECTO_IPV6 = 'true'
  ELIXIR_ERL_OPTIONS = '+fnu'
  LANG = 'en_US.UTF-8'
  LC_ALL = 'en_US.UTF-8'
  MIX_ENV = 'prod'
  PHX_HOST = 'bgg-sorter.fly.dev'
  PHX_SERVER = 'true'
  POOL_SIZE = '10'
  PORT = '7384'

[http_service]
  internal_port = 7384
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[[statics]]
  guest_path = '/app/lib/web-*/priv/static'
  url_prefix = '/static/'
